### ISSUE TITLE
Switch to Key/Mouse EventHandlers

### ISSUE THREAD

**Issue by razaqq** [VincentFoulon80/console_engine#10]
**Is your feature request related to a problem? Please describe.**
The current implementation means at only the moment `is_key_pressed` or `get_mouse_press` are called the state of the key/mouse is checked. This is a simple solution, but also introduces delays and at low framerates entire keypresses might go unnoticed.

**Describe the solution you'd like**
It would be significantly better if you were to hook/unhook eventHandlers to keys/mouse events, instead of checking in an endless loop.
Implementing `on_key_down(Key, Function)`, `on_key_up(Key, Function)`, `on_mouse_move(Function)`, ...

**Comment by VincentFoulon80** [comment]
One of the first goal of the project is to have a procedural approach, I didn't intend to do events due to me being unskilled at first (I learned Rust with this project) and also due to potential variable access problems.
For example, how can I give you access to your variables in the event function ? We may need to define something in the middle to allow that. 🤔 This may require `async` properties to the project

Do you have by any chance any experience in it ?

By the way, we capture inputs when the engine is idling, so only on `wait_frame` 😉

**Comment by razaqq** [comment]
ill check it when i get some time

**Comment by VincentFoulon80** [comment]
Hello @razaqq !

I made a [pull request](https://github.com/VincentFoulon80/console_engine/pull/12) that add some sort of event handling. Can you take a look at it and tell me if it's resolving your issue, please ?

**Comment by VincentFoulon80** [comment]
The pull request has been merged! see [Release 2.1.0](https://github.com/VincentFoulon80/console_engine/releases/tag/2.1.0)
